### PR TITLE
Add support for downloading playlists on user downloads

### PR DESCRIPTION
**Pull request by KleaTech**
Configurable on the UI. If checkbox is ticked user downloads will download that user's playlists too.

### CODE REVIEW

**Comment by Tenpi** [comment]
Only thing is that I would name it something shorter like "User Playlists?". Thanks for your contribution.

**Comment by Tenpi** [comment]
This line might fall into an infinite loop if the person has more than 100 playlists.
```js
while (playlists.next_href) {
  playlists = await fetch(`https://api-v2.soundcloud.com/users/${request.user.id}/playlists?client_id=${clientID}&limit=100`).then(r => r.json())
  playlistArray.push(...playlists.collection)
}
```
To avoid the possibility of falling into an infinite loop, you must search the `next_href` provided by soundcloud.
```js
while (playlists.next_href) {
  playlists = await fetch(`${playlists.next_href}&client_id=${clientID}`).then(r => r.json())
  playlistArray.push(...playlists.collection)
}
```

**Comment by Tenpi** [comment]
Also, this doesn't seem to include private playlists. It's not a huge issue though, they just don't seem to appear in the API call.

**Comment by KleaTech** [comment]
I missed the next_href issue, it was a copy paste error. I see that you fixed it.
I'm not sure about private playlists. I guess these are not visible on a user's feed hence are private. If so, I don't think there are any API to return them. Maybe a user would be able to download their own private playlists, but that's an edge case. If you have a link to a private playlist you can probably download it with the playlist download feature instead of the user download feature.

**Pull request merged**
