### PR TITLE
popup window improvements

### PR DESCRIPTION
**Pull request by Fasteroid**
image
+ The checkboxes are now toggle switches!
+ All colors now link to two CSS variables so they're easier to change!
+ Added categories for better descriptions of what things do.

### CODE REVIEW

**Comment by Fasteroid** [comment]
Btw, I did my testing on Chromium.  Not sure if it works in Firefox, but like, there's no reason it shouldn't.

**Comment by Tenpi** [comment]
Thanks for improving the popup, just a couple nitpicks that I’ll fix:
-The extension is called “Soundcloud Download”, not “Soundcloud Downloader”
-I prefer to have question marks eg. “Enable?” Instead of “Enable”
-I would like the title to be colored

**Comment by Fasteroid** [comment]
> Thanks for improving the popup, just a couple nitpicks that I’ll fix:
> 
> * The extension is called “Soundcloud Download”, not “Soundcloud Downloader”
> * I prefer to have question marks eg. “Enable?” Instead of “Enable”
> * I would like the title to be colored

Would've revised this PR to your liking but it's already merged now, bah.
No big deal I guess, just means you've gotta do this now.  Best of luck!

**Comment by Tenpi** [comment]
Ok it seems like Chrome updated their store policies and my extension goes against it by offering access to "unauthorized content on https://www.soundcloud.com" so unfortunately this update won't be pushed onto the chrome store. I am not sure if they will remove it soon. 

In the future you will have to download the zip and load this as a unpacked extension:
https://github.com/Tenpi/soundcloud-download/releases

**Comment by Fasteroid** [comment]
Already was doing this since I suspected it might get taken down :)
________________________________

**Pull request merged**
